package com.cinema.application.dto.enums;

public enum FilteringOption {
    GENRE,DURATION,TITLE,
    BY_MONTHS_TRANSACTION_DATE,BY_PRICE, BY_DISCOUNT, BY_MOVIE_TITLE,BY_PLACE,BY_MONTHS_SEANCE_DATE, BY_MOVIE_GENRE
}
